name: Build my app

on: push

jobs:
  super-lint:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v2
      - name: Print current dir
        run: pwd
      - name: list of files in dir 
        run: ls
          